import "../styles/global/global.scss";
import "../styles/themes/themes.scss";
import Header from "./components/header";

export const metadata = {
  title: "Bergen Candle",
  description: "Generated by create next app",
  alternates: {
    languages: {
      'en': '/',
      'no': '/no',
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/tdx0xkz.css" />
      </head>
      <body className="l-site theme">
        <Header/>
        {children}
      </body>
    </html>
  );
}
